# Base image
FROM node:22.19.0-alpine

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Bundle app source
COPY . ./

# Install app dependencies
RUN npm install

# Copy the .env and .env.development files
# COPY app/.env app/.env.development ./

# Creates a "dist" folder with the production build
# RUN npm run build

# Expose the port on which the app will run
EXPOSE 3000

# Start the server using the dev build
CMD ["npm", "run", "start:dev"]
